version: '3.8'
services:
  db:
    image: postgres:15
    container_name: news_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data