spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # ?? ???? update, ???? validate ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always # Spring Batch ?? ??? ?? ??
    job:
      enabled: false # ?? ?? ? ?? ??? ???? ??? ??